Integration test reports

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -54,6 +54,7 @@ jobs:
           # output: /tmp/foo.txt
           # Fail action on broken links
           fail: true
+          jobSummary: false
       - name: Build docker
         run: ./gradlew :java:runner:dockerBuildImageAll
         env:
@@ -83,7 +84,8 @@ jobs:
           name: Test Report
       - name: Run Integration tests
         run: |
-          ./gradlew intTest
+          ./gradlew intTest || true
+        # some connectors may fail, see summary to track failed connectors.
       - name: Upload Integration test results
         if: always()
         uses: actions/upload-artifact@v2
@@ -100,6 +102,7 @@ jobs:
           path: ./java/runner/build/test-results/intTest/*.xml
           reporter: java-junit
           fail-on-error: false
-      - name: Adding to summary
+          only-summary: true
+      - name: Adding reports to summary
         if: always()
-        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
+        run: echo "$(cat ./java/runner/build/test-reports.md)" >> $GITHUB_STEP_SUMMARY
